// ===== Sample Marketing Terms. Replace/extend with your full list later. =====
const terms = [
  { word: "A/B Testing", definition: "Comparing two versions of content or campaigns to see which performs better." },
  { word: "Above the Line Marketing", definition: "Mass media advertising such as TV, radio, or print." },
  { word: "Account-Based Marketing", definition: "Focusing marketing efforts on key accounts instead of broad audiences." },
  { word: "Acquisition Cost", definition: "The total cost of acquiring a new customer." },
  { word: "Ad Impressions", definition: "The number of times an ad is displayed to users." },
  { word: "Affiliate Marketing", definition: "Earning commission by promoting other companies products." },
  { word: "Agile Marketing", definition: "Using agile principles to quickly adapt marketing strategies." },
  { word: "Ambush Marketing", definition: "Branding around an event without being an official sponsor." },
  { word: "Analytics", definition: "The process of measuring and analyzing marketing data." },
  { word: "Annual Recurring Revenue", definition: "Revenue that is expected every year from subscriptions." },
  { word: "Attribution Model", definition: "Method of assigning credit to marketing touchpoints for conversions." },
  { word: "Awareness Stage", definition: "First stage in customer journey where buyers recognize a problem." },
  { word: "B2B Marketing", definition: "Marketing products or services to businesses." },
  { word: "B2C Marketing", definition: "Marketing products or services to individual consumers." },
  { word: "Backlinking", definition: "Links from other websites pointing to your site for SEO." },
  { word: "Banner Ads", definition: "Display ads on websites in rectangular or square formats." },
  { word: "Behavioral Targeting", definition: "Using consumer behavior data to deliver relevant ads." },
  { word: "Benchmarking", definition: "Comparing performance against competitors or industry standards." },
  { word: "Big Data Marketing", definition: "Using large-scale data to drive marketing insights." },
  { word: "Blog Marketing", definition: "Promoting products or services through blogs." },
  { word: "Bounce Rate", definition: "Percentage of visitors who leave after viewing one page." },
  { word: "Brand Advocacy", definition: "When loyal customers actively promote a brand." },
  { word: "Brand Awareness", definition: "How well customers recognize and recall a brand." },
  { word: "Brand Equity", definition: "Value added to a product by its brand reputation." },
  { word: "Brand Extension", definition: "Using an existing brand to launch a new product." },
  { word: "Brand Loyalty", definition: "Customer preference for one brand over competitors." },
  { word: "Brand Positioning", definition: "The unique space a brand occupies in the consumers mind." },
  { word: "Brand Recall", definition: "Ability of consumers to remember a brand name." },
  { word: "Brand Recognition", definition: "How easily customers identify a brand visually or verbally." },
  { word: "Buzz Marketing", definition: "Generating word-of-mouth excitement for a product." },
  { word: "Call to Action", definition: "Instruction encouraging consumers to take action, like 'Buy Now'." },
  { word: "Campaign Management", definition: "Planning, executing, and monitoring marketing campaigns." },
  { word: "Churn Rate", definition: "Percentage of customers lost in a given time period." },
  { word: "Click-Through Rate", definition: "Percentage of people clicking an ad after seeing it." },
  { word: "Closed-Loop Marketing", definition: "Tracking customers from initial contact to final sale." },
  { word: "Community Marketing", definition: "Engaging with online or offline communities to build loyalty." },
  { word: "Content Curation", definition: "Collecting and sharing valuable third-party content." },
  { word: "Content Marketing", definition: "Creating and distributing valuable content to attract customers." },
  { word: "Conversion Funnel", definition: "Stages customers go through before making a purchase." },
  { word: "Conversion Rate", definition: "Percentage of visitors who take a desired action." },
  { word: "Co-Branding", definition: "Two brands partnering to create joint marketing." },
  { word: "Corporate Branding", definition: "Promoting the companys brand as a whole." },
  { word: "Cost Per Acquisition", definition: "Marketing cost to acquire one paying customer." },
  { word: "Cost Per Click", definition: "The price paid for each click in online ads." },
  { word: "Cost Per Lead", definition: "Amount spent to generate one lead." },
  { word: "CRM", definition: "Customer Relationship Management, systems for managing interactions." },
  { word: "Cross-Promotion", definition: "Promoting products across different platforms or brands." },
  { word: "Crowdsourced Marketing", definition: "Getting marketing ideas or content from the public." },
  { word: "Customer Experience", definition: "Overall perception of customers interactions with a brand." },
  { word: "Customer Journey", definition: "Path customers follow from awareness to purchase." },
  { word: "Customer Lifetime Value", definition: "Total revenue expected from one customer over time." },
  { word: "Customer Retention", definition: "Efforts to keep customers coming back." },
  { word: "Data-Driven Marketing", definition: "Using analytics and insights to guide marketing." },
  { word: "Demographic Segmentation", definition: "Dividing markets based on age, gender, income, etc." },
  { word: "Digital Marketing", definition: "Using digital channels to promote products." },
  { word: "Direct Marketing", definition: "Reaching customers directly via email, SMS, or mail." },
  { word: "Display Advertising", definition: "Banner ads shown on websites or apps." },
  { word: "Downselling", definition: "Offering a cheaper alternative to retain customers." },
  { word: "Drip Marketing", definition: "Sending pre-scheduled marketing messages to leads." },
  { word: "Dynamic Pricing", definition: "Adjusting prices based on demand or behavior." },
  { word: "Earned Media", definition: "Publicity gained without paid promotion." },
  { word: "Email Marketing", definition: "Sending promotional messages via email." },
  { word: "Engagement Rate", definition: "Level of interaction with online content." },
  { word: "Event Marketing", definition: "Promoting brands through live events." },
  { word: "Experiential Marketing", definition: "Creating experiences to engage customers directly." },
  { word: "Eye-Tracking", definition: "Measuring where users look on a screen or ad." },
  { word: "Focus Group", definition: "Small group discussion for customer feedback." },
  { word: "Forecasting", definition: "Predicting future sales or demand." },
  { word: "Freemium Model", definition: "Offering free basic services and charging for premium features." },
  { word: "Geo-Targeting", definition: "Delivering ads based on geographic location." },
  { word: "Guerrilla Marketing", definition: "Unconventional, low-cost marketing tactics." },
  { word: "Inbound Marketing", definition: "Attracting customers through valuable content." },
  { word: "Influencer Marketing", definition: "Partnering with influencers to promote products." },
  { word: "Integrated Marketing", definition: "Coordinating messages across all marketing channels." },
  { word: "Interactive Marketing", definition: "Two-way communication between brand and customer." },
  { word: "Key Performance Indicator", definition: "Metrics used to measure marketing success." },
  { word: "Landing Page", definition: "A web page designed for lead generation or conversions." },
  { word: "Lead Generation", definition: "Attracting and converting prospects into leads." },
  { word: "Lead Nurturing", definition: "Building relationships with leads over time." },
  { word: "Lifetime Value", definition: "Revenue expected from a single customer during their lifetime." },
  { word: "Loyalty Program", definition: "Rewards program to retain customers." },
  { word: "Market Penetration", definition: "Increasing market share with existing products." },
  { word: "Market Research", definition: "Collecting data to understand customer needs." },
  { word: "Market Segmentation", definition: "Dividing markets into smaller groups of buyers." },
  { word: "Marketing Analytics", definition: "Measuring and analyzing marketing performance." },
  { word: "Marketing Automation", definition: "Software to automate repetitive marketing tasks." },
  { word: "Marketing Mix", definition: "Combination of 4Ps: Product, Price, Place, Promotion." },
  { word: "Native Advertising", definition: "Ads that blend into the platforms content style." },
  { word: "Net Promoter Score", definition: "Metric that measures customer loyalty and satisfaction." },
  { word: "Neuromarketing", definition: "Applying neuroscience to understand consumer behavior." },
  { word: "Omnichannel Marketing", definition: "Integrated marketing across multiple platforms." },
  { word: "Organic Reach", definition: "Number of people who see content without paid promotion." },
  { word: "Outbound Marketing", definition: "Pushing messages out through ads, calls, or emails." },
  { word: "Paid Media", definition: "Advertising that costs money, like PPC or display ads." },
  { word: "Persona", definition: "Fictional character representing a customer type." },
  { word: "Personalization", definition: "Tailoring marketing messages to individual customers." },
  { word: "Positioning", definition: "How a brand is perceived in the minds of customers." },
  { word: "Predictive Analytics", definition: "Using past data to forecast future behavior." },
  { word: "Product Life Cycle", definition: "Stages a product goes through from launch to decline." },
  { word: "Programmatic Advertising", definition: "Automated real-time buying of digital ads." },
  { word: "Public Relations", definition: "Managing a brands reputation and public image." },
  { word: "Referral Marketing", definition: "Encouraging customers to refer new clients." },
  { word: "Remarketing", definition: "Showing ads to users who visited your site before." },
  { word: "Retention Rate", definition: "Percentage of customers who continue using a product." },
  { word: "Return on Ad Spend", definition: "Revenue generated for each rupee spent on ads." },
  { word: "Return on Investment", definition: "Profit earned from marketing compared to cost." },
  { word: "Sales Funnel", definition: "Stages from lead to paying customer." },
  { word: "Search Engine Marketing", definition: "Paid promotion on search engines like Google." },
  { word: "Search Engine Optimization", definition: "Optimizing content to rank higher in search engines." },
  { word: "Sentiment Analysis", definition: "Measuring opinions and emotions in customer feedback." },
  { word: "Share of Voice", definition: "Brands visibility compared to competitors." },
  { word: "Social Listening", definition: "Monitoring conversations on social media." },
  { word: "Social Media Marketing", definition: "Using social media platforms for promotions." },
  { word: "Sponsorship Marketing", definition: "Supporting events or activities for promotion." },
  { word: "Storytelling", definition: "Using narratives to build emotional connections." },
  { word: "SWOT Analysis", definition: "Identifying Strengths, Weaknesses, Opportunities, and Threats." },
  { word: "Target Audience", definition: "Specific group of customers a company aims to reach." },
  { word: "Test Marketing", definition: "Launching a product in a limited market to test." },
  { word: "Thought Leadership", definition: "Positioning a brand as an expert in the field." },
  { word: "Upselling", definition: "Encouraging customers to buy a more expensive option." },
  { word: "User-Generated Content", definition: "Content created by customers that promotes a brand." },
  { word: "Value Proposition", definition: "Unique benefit a product offers to customers." },
  { word: "Viral Marketing", definition: "Content spreading rapidly like a virus online." },
  { word: "Voice Search Optimization", definition: "Adapting content for voice-based searches." },
  { word: "Web Analytics", definition: "Tracking and analyzing website performance." },
  { word: "Word of Mouth Marketing", definition: "Customers sharing opinions and experiences." },
  { word: "Zero Moment of Truth", definition: "The moment a consumer researches online before purchase." },
  { word: "Push Strategy", definition: "A strategy where products are pushed through the distribution channel to the final consumers using promotions and direct selling." },
  { word: "Pull Strategy", definition: "A strategy aimed at creating strong consumer demand so that customers actively seek out a product, pulling it through the distribution channel." },
  { word: "Up Strategy", definition: "Encouraging customers to move towards higher-value or premium products to increase revenue." },
  { word: "Down Strategy", definition: "Offering customers lower-priced alternatives to retain them when they are unwilling to purchase premium products." },
  { word: "Cross Selling", definition: "Selling related or complementary products to existing customers to maximize value." }
  { word: "AIDA", definition: "Attention, Interest, Desire, Action — a classic model describing the stages a consumer goes through before purchase." },
];
